apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: binnacle
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: binaccle
            image: scottbrenner/binnacle:latest
            imagePullPolicy: Never
          restartPolicy: OnFailure      